version: "3.9"
services:
  psq_1:
    container_name: psql_1
    image: postgres:alpine
    environment:
      POSTGRES_DB: "user_segmentation"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username <USER> --dbname <DB_NAME>"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
